# Generated by Django 5.1.5 on 2026-09-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_customuser_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
