# Generated by Django 6.1 on 2026-09-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0017_deliveryrequest_dest_lat_deliveryrequest_dest_lng_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverymessage',
            options={'ordering': ['timestamp', 'id']},
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='dest_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='dest_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
