# Generated by Django 6.1 on 2026-09-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0018_alter_deliverymessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='rider_acc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderlocationpoint',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
