# Generated by Django 6.1 on 2026-09-28 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, default='System', max_length=150)),
                ('category', models.CharField(choices=[('ORDER', 'Orders'), ('MENU', 'Menu & Stock'), ('PAYMENT', 'Payments'), ('USER', 'User Management'), ('DELIVERY', 'Deliveries'), ('SYSTEM', 'System')], db_index=True, max_length=20)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('DANGER', 'Critical')], db_index=True, default='INFO', max_length=10)),
                ('action', models.CharField(max_length=255)),
                ('target', models.CharField(blank=True, default='', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_guest', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log Entry',
                'verbose_name_plural': 'Activity Log Entries',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_log_recent_idx'), models.Index(fields=['category', '-created_at'], name='activity_log_cat_time_idx')],
            },
        ),
    ]
